SELECT
  cu.*
FROM
[master].[INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] AS cu
INNER JOIN
(
  SELECT * FROM
  [master].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS]
    WHERE
    [master].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS].[CONSTRAINT_TYPE] = "FOREIGN KEY"
) AS tc
ON
cu.[CONSTRAINT_NAME] = tc.[CONSTRAINT_NAME]
WHERE
cu.[TABLE_SCHEMA] = :database
AND
cu.[TABLE_NAME] = :table
